# Generated by Django 3.2.6 on 2021-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('authentication', '0002_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='bought_books', to='library.BookInfo'),
        ),
    ]
